### ISSUE TITLE
Convert TODOs into Issues

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#1]
The code has a lot of TODOs as it was developed without an issue tracker.

1. Find TODO comment in code
2. For each TODO create an issue
3. Remove TODO comment from code

**Comment by rajdhandus** [comment]
thanks @nishakm .. I am on it..

**Comment by rajdhandus** [comment]
I grepped for any literal named 'todo'.. i am not able to find any in the 'tern' repo.. can you please point me to one?

**Comment by nishakm** [comment]
https://github.com/vmware/tern/search?utf8=%E2%9C%93&q=TODO&type=

**Comment by nishakm** [comment]
@rajdhandus also, when creating issues, make sure there isn't an existing issue like it. If there is an existing issue, you can refer to it in your PR.
