### ISSUE TITLE
Similar project, different approach

### ISSUE THREAD

**Issue by pombredanne** [vmware/tern#12]
Hi!
Dirk pointed me to this project which is awesome.
I maintain a fledgling thing called conan https://github.com/nexB/conan with the same goals, same tech and a slightly different approach.... Should be collaborate somehow?

**Comment by nishakm** [comment]
Hi @pombredanne! Thanks for getting in touch. Can we move this conversation to the google groups forum? https://groups.google.com/forum/#!forum/tern-maintainers

**Comment by nishakm** [comment]
Conversation moved to the forum: https://groups.google.com/forum/#!topic/tern-maintainers/xPPGwkgoQ2U
