### ISSUE TITLE
Classes with lists of objects should check if the objects are instances of the objects they are supposed to contain

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#13]
Currently the classes append whatever object is passed to it. Add a check to the add_* methods that check if the object is an instance of the class they are supposed to hold.
Perhaps raise a TypeError when there is a mismatch.

**Comment by jackey8616** [comment]
@nishakm  hi there, i would like to take this issue.
Now is on progress.

**Comment by jackey8616** [comment]
Hi @nishakm , i have already done with some code.
But there is some errors while running tests.

I modified image_layer.py, notice_origin.py, and origins.py files in classes folder.
After checking tests folder and there is only some test file like test_class_image_layer.py, test_class_image.pyand test_class_notice.py are most relative with the file i modified, so i run these test.
But there is something wrong.

```
$ python tests/test_class_image_layer.py

E....E
======================================================================
ERROR: testAddNotice (_main_.TestClassImageLayer)
----------------------------------------------------------------------
Traceback (most recent call last):
 File "tests/test_class_image_layer.py", line 48, in testAddNotice
   self.layer.add_notice(n)
AttributeError: 'ImageLayer' object has no attribute 'add_notice'

======================================================================
ERROR: testToDict (_main_.TestClassImageLayer)
----------------------------------------------------------------------
Traceback (most recent call last):
 File "tests/test_class_image_layer.py", line 55, in testToDict
   self.assertTrue(a_dict['123abc'])
KeyError: '123abc'

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=2)
```

```
$ python tests/test_class_image.py

E
======================================================================
ERROR: testInstance (_main_.TestClassImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_class_image.py", line 21, in testInstance
    self.assertEqual(self.image.repotag, 'debian:jessie')
AttributeError: 'Image' object has no attribute 'repotag'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

```
$ python tests/test_class_notice.py

.E.
======================================================================
ERROR: testInstance (_main_.TestClassNotice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_class_notice.py", line 21, in testInstance
    self.assertFalse(self.notice.origin)
AttributeError: 'Notice' object has no attribute 'origin'

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (errors=1)
```

These error also appears with origin repo without any modified codes.
So please give me some opinion to solve this.

Is this O.K. to send a PR, or something else.
My code is [HERE](https://github.com/jackey8616/tern/commit/753bba4dea18a2c59a7b6ec84439bd70017bca6b)

Big Thx.

**Comment by nishakm** [comment]
@jackey8616 Thanks for the PR! The unit tests are outdated for the most part since the last release and I need to fix them. For now, if you want to manually test out your changes for each of the classes, I would accept a PR with just those changes.

**Comment by nishakm** [comment]
@jackey8616 just let me know if you want to continue working on this, and I will mark it as assigned. Thanks again!

**Comment by jackey8616** [comment]
If these changes is healthy. I'd like to send out PR. :smiley:

**Comment by nishakm** [comment]
Resolved in https://github.com/vmware/tern/pull/94. Thanks again!
