### ISSUE TITLE
Run tests on PRs based on files touched

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#139]
Travis CI currently doesn't support triggering tests based on what files were touched by a PR. However, there must be some kind of hack for this.

This will help speed up testing for PRs. This would also be a forcing function to manage the tests better.

**Comment by nishakm** [comment]
Found an example on how to do this: https://github.com/dev-id/Magic-Spoiler/blob/8111a06ab6682e020169991d5e2aa4fa503d787f/preflight.sh

**Comment by nishakm** [comment]
Closing this issue due to the Travis CI news (no official announcement has been made but apparently their core team has been laid off)

**Comment by nishakm** [comment]
Reopened issue - implementing this using Circle CI now. There is a possibility of using an orb here but this needs investigation

**Comment by nishakm** [comment]
We haven't found an orb that does this. Falling back to figuring out how to write conditional tests.

**Comment by nishakm** [comment]
https://github.com/CircleCI-Public/config-preview-sdk/blob/0d39520bb81ffac555c3ec75f616aa4f8e2e697b/docs/conditional-steps.md#conditional-steps

Means the condition needs to be predefined (not evaluated at runtime) which we cannot do. So this has to be written as a test.

**Comment by rnjudge** [comment]
Manually closing. This change was resolved in #318
