### ISSUE TITLE
Script error "error: chroot: failed to run command"

### ISSUE THREAD

**Issue by yahalom5776** [vmware/tern#159]
Hello Nisha,

we get a script error when running tern 0.2.0 against Docker images, e.g for rancher/calico-node

```
This report was generated by the Tern Project
https://github.com/vmware/tern/commit/d36f6cee865f8bf8e1e6a8069778a2837552de07

Docker image: <internal identifier removed>/rancher/calico-node:v3.1.1:
	Layer: 84f2da658a:
		info: Layer created by commands: /bin/sh -c #(nop) ADD file:093f0723fa46f6cdbd6f7bd146448bb70ecce54254c35701feeceb956414622f in / 
		info: Using invoke listing in command_lib/base.yml
names:
	in container:
	apk info 2>/dev/null

versions:
	in container:
	pkgs=`apk info 2>/dev/null`
	for p in $pkgs; do apk info $p 2>/dev/null | head -1 | awk '{print $1}'; done

licenses:
	in container:
	pkgs=`apk info 2>/dev/null`
	for p in $pkgs; do apk -a info $p 2>/dev/null | tail -2 | head -1; done

src_urls:
	in container:
	pkgs=`apk info 2>/dev/null`
	for p in $pkgs; do apk info $p 2>/dev/null | head -5 | tail -1; done



		error: chroot: failed to run command ‘/bin/sh’: Exec format error
chroot: failed to run command ‘/bin/sh’: Exec format error
chroot: failed to run command ‘/bin/sh’: Exec format error
chroot: failed to run command ‘/bin/sh’: Exec format error

------------------------------------------------
```

The image is pulled from an internal Artifactory repo, tern is set up within a VM based on Ubuntu Server 16.04 LTS.

Perhaps you can point us in the right direction here. Thank you!

**Comment by nishakm** [comment]
@yahalom5776 can you share your image name and tag?

**Comment by yahalom5776** [comment]
@nishakm 
An example is 

`rancher/calico-node:v3.1.1`

I just removed the URL of our internal registry from the output above.

**Comment by nishakm** [comment]
@yahalom5776 is there an equivalent on Dockerhub? It looks to me that your image is based on Alpine but may be missing `awk`

**Comment by nishakm** [comment]
Also, can you share the results of `arch` and `python3 --version`?

**Comment by yahalom5776** [comment]
@nishakm the official DockerHub Image is here: https://hub.docker.com/r/rancher/calico-node

Output of `arch`: 

`i686`

Output of `python3 --version`:

`Python 3.5.2`

It might be a problem with the bitness, we will try a x64 VM and report back.

**Comment by yahalom5776** [comment]
@nishakm the scan works with tern running in a x64 VM. I will close this issue.
