### ISSUE TITLE
Make Tern report what repo style and distro the container image is based off

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#161]
**Describe the Feature**
For example:
```
Docker image: tern:0.2.0:
        Layer: b21d36aa7a:
                info: Layer created by commands: /bin/sh -c #(nop) ADD file:332992a7a5fc30e945030fa1a60c21378848dc4c7269c67dc38505e1afe0c8bc in /
               info: Found 'dpkg' possible OSs are debian, ubuntu
                info: Using invoke listing in command_lib/base.yml
```

**Use Cases**
Since the original repo's information is lost, this might give folks an idea of what kind of OS image their starting image is based on

**Implementation Changes**
- Add a listing in the command library that lists the possible os's
- Add report message that says something like `'Found {}'.format(binary)`
- For Package and Image add a new property: pkg_format
This indicates what repository the package may have come from
- Add notice about this

**Comment by joshuagl** [comment]
Before guessing what the OS is based on the package manager you could check the [`os-release`](https://www.freedesktop.org/software/systemd/man/os-release.html) file, which is a standard configuration file in modern Linux-based OS. 

Where the container builder hasn't stripped this as an extraneous file you'll get much more complete results, not only can you determine the exact distro and version with the `ID` and `VERSION` fields but you can also determine when a distro is a derivative of another distro with the `ID_LIKE` field (i.e. Ubuntu is `ID_LIKE=debian` whilst CentOS is `ID_LIKE = "rhel fedora"`). 

See the [`os-release(5)`](https://www.freedesktop.org/software/systemd/man/os-release.html) manual page and the original blog post [announcing the configuration file](http://0pointer.de/blog/projects/os-release).

**Comment by rnjudge** [comment]
I think this a good point that /etc/os-release will have the most reliable information. While this file may not always be present in a container image, I agree that we should at least check the file and if it does not exist we can fall back on base.yml for suggestions. Thanks, Josh!
