### ISSUE TITLE
Enable SPDX document output

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#174]
**Problem Statement**
SPDX documents describe metadata about an artifact in relation to their sources, build and run dependencies. More information can be found here: https://spdx.org/using-spdx-documents. 

**Describe the Proposal**
Enable Tern to print out a document in SPDX format

**Steps to Implement Proposal**
Tern has its own schema to describe components plus some additional schema to describe instances and observations. Some document mapping one to the other is needed. #163 may be able to help here. If yes, then defining the YAML to YAML mapping for SPDX may be enough. If there are missing identifiers for the package, then they can be added to the `classes/package.py` class.

**Comment by nishakm** [comment]
So, SPDX doesn't support YAML at this time (and will probably not for some time to come). They have a tag-value format that would probably need to be handled outside the way that the custom converter would handle things. Need arch document for this.

**Comment by swinslow** [comment]
Hi @nishakm, I’m interested in helping with this. I’m involved with the SPDX project and have written some tooling for handling its tag-value format (Golang and Python). I’m getting more familiar with Tern and would be glad to help with an arch document here.

**Comment by nishakm** [comment]
@swinslow Thank you! The best way to find what kinds of "elements" are supported right now, take a look at `src/classes`. Basically, image -> layer list, layer -> package list and package is the most basic class. I'll need to basically find a mapping for each of the properties to an SPDX tag. And then find mandatory SPDX tags not in the class properties. Ignore "Origins", "NoticeOrigin" and "Notice" classes -> they're meant for informational purposes and map to comments in SPDX.

Am I wrong in assuming that SPDX tools doesn't support YAML to SPDX right now? It would be really nice to just feed the tool a YAML document and have it convert it to SPDX.

**Comment by swinslow** [comment]
Thanks @nishakm! I’ll dig into this, and will circle back with thoughts. 

Yes, the SPDX spec doesn’t have a YAML format defined, and to my knowledge the current official SPDX tools (Java, Python, Golang) don’t translate to or from YAML. There are goals to add JSON as an official format in an upcoming spec release, but I’m not sure what the timeframe will be for this.

**Comment by nishakm** [comment]
After thinking about it for a bit, I think it is possible to use the custom template workflow described in #180 would work for converting to tag value. Rather than use a dictionary and use yaml.dump, use a string and write to stdout.

**Comment by nishakm** [comment]
Once review of PR https://github.com/vmware/tern/pull/270 is done, we can resolve this.

**Comment by nishakm** [comment]
PR #270 review and fixes is done. Resolving.
