### ISSUE TITLE
Please enable rpm support

### ISSUE THREAD

**Issue by rothgar** [vmware/tern#181]
Would be nice to be able to use this for CentOS, Red Hat, Amazon Linux, and fedora based images.

**Comment by nishakm** [comment]
Thanks for filing the issue! If you know how to list installed packages using rpm, enabling rpm support is pretty straightforward. You will just need to add a listing in `https://github.com/vmware/tern/blob/master/src/command_lib/base.yml` for `rpm` and find scripts to list out names, versions and licenses. Would you be willing to help out with this?

**Comment by rothgar** [comment]
I know the commands for listing packages and will check on outputting license information. I'll try to pr it later this week.

**Comment by nishakm** [comment]
@rothgar If you're looking for a template on how to enable rpm support, this PR is a good one: https://github.com/vmware/tern/pull/189
