### ISSUE TITLE
Add checksum as a Package property

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#183]
**Describe the Feature**
Add `checksum` as a Package property.

**Use Cases**
Specifically, this is a property that SPDX documents use. More generally, This is a good way to check for any discrepancies even if the package manager has the same metadata and can detect some corner cases for diffs. See PR #182 conversations for more context.

**Implementation Changes**
1. Add the checksum property to Package class with a default value (empty string)
2. Find methods for each of the package manager supported to get this information

**Comment by khayamgondal** [comment]
@nishakm Is it stil open? I can take it.

**Comment by rnjudge** [comment]
Nisha is out until July 22nd and we will review all PRs once she returns but this issue is still open. Please feel free to work on it.

**Comment by khayamgondal** [comment]
@r-raghu who /where can I find the supported package managers and methods to get them?

**Comment by khayamgondal** [comment]
@rnjudge @nishakm can you guide me where exaclty in code we retrive the pacakge information?

**Comment by rnjudge** [comment]
@khayamgondal The Package class under tern/classes/package.py is where all of the information related to a package will be. This is where you will want to add the checksum property as well.

**Comment by nishakm** [comment]
@rnjudge This looks good to me, but I'd like you to take a look as well to see if I haven't missed anything.
