### ISSUE TITLE
Resolve code style issues with the code base

### ISSUE THREAD

**Issue by mkrohan** [vmware/tern#191]
Standard Python style/code checkers report issues with the code base.  The
utility "prospector" can be used to report issues from a collection of style/code
checkers (default list is "dodgy, mccabe, pep8, profile-validator, pyflakes, pylint",
note, pep8 has been renamed pycodestyle).  When run on the src directory,
it reports 76 issues.  The majority are trivial.

I propose:
* a "dev-requirements.txt" file to pull development oriented dependencies (prospector)
* fixing issues with each file that are (some will likely be deferred on the initial pass)

This will be a series of pull requests keeping changes to small, easily reviewed requests.

**Comment by nishakm** [comment]
Prospector also seems to have support for [pre-commit](https://pre-commit.com/#usage). Pre-commit sounds really cool! If it works out for this project, would you mind rolling this change into the pre-commit config? https://github.com/PyCQA/prospector#pre-commit

`dev-requirements.txt` sounds like a nice addition to development tools as well.

**Comment by mkrohan** [comment]
Will investigate the pre-commit hook once all the issues it currently raises are resolved.

**Comment by nishakm** [comment]
Still need to document how to lint code in `CONTRIBUTING.md`
