### ISSUE TITLE
Add source file encoding comments

### ISSUE THREAD

**Issue by mkrohan** [vmware/tern#197]
Tern source files should explicitly indicate they are UTF-8 encoded.  At this point, it seems,
all sources are simple ASCII files.  While i18n considerations are low, non-ASCII can easily
slip in, e.g., a including arrow symbols to highlight issues.

Python has a PEP for this, see https://www.python.org/dev/peps/pep-0263/

Annotate the sources with the comment "# -*- coding: utf-8 -*-" which covers both Python
and most editors.

**Comment by nishakm** [comment]
@mkrohan do you mind if I put this out as a good-first-issue for a beginner open source contributor?

**Comment by mkrohan** [comment]
Sure, that would be OK.

**Comment by oransimhony** [comment]
Hi!
I've added `# -- coding: utf-8 --` to all python files (excluding `__init__.py` files).
If you want me to add the annotation to `__init__.py` files as well just tell me :)
Would you mind telling me how can I run the tests to make sure I hadn't broken anything before I submit a pull request?
Thanks!

**Comment by mkrohan** [comment]
Apologies, GitHub markdown consumed some of the comment.  The string that should be added is "` -*- coding: utf-8 -*-`".  See, e.g., https://github.com/vmware/django-yamlconf/blob/master/django_yamlconf/__init__.py  I normally tag init files also as they can contain code.

**Comment by oransimhony** [comment]
Hi, 
I fixed the comments and added them to `__init__.py` files as well.
I've sent a pull request, please tell me if there's anything else I should do.

**Comment by nishakm** [comment]
Resolved in 83049be6b0b693a90570beac03cc71564133d959
