### ISSUE TITLE
Unix command parser does not parse version or arch specified in the package name

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#2]
For example: apt-get install package:arch=version

If the package has a version then record it in the returning dict as 'version': version. If the package has an arch, record it in the returning dict as 'arch':

**Comment by rnjudge** [comment]
@nishakm When you say "record it in the returning dict as 'version': version." which dict are you referring to? A dictionary returned by a new function that will parse the package name?

**Comment by rnjudge** [comment]
@nishakm You also said yesterday that you can't see any reason we would need to store the version of a package :) Should we still store it?

**Comment by nishakm** [comment]
> @nishakm You also said yesterday that you can't see any reason we would need to store the version of a package :) Should we still store it?

I filed this two years ago :D. I'll let you make that judgement call.
