### ISSUE TITLE
Rename `id` and `license` class properties

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#213]
**Problem Statement**
`id` and `license` are built-in Python objects. PR #203 dismisses them but for clarity, they need to be renamed to something else. `image_id and `pkg_license` sounds like the most straightforward thing. 

**Describe the Proposal**
Rename properties `id` and `license` in all classes. Then rename the references throughout the code.

**Comment by ManishaTripathy** [comment]
Hi , is it still an open issue? i would like to work on it

**Comment by nishakm** [comment]
@ManishaTripathy sure, go for it! Here's what you'll need to do:
1. Find within `tern/classes` all classes that have a property called `id` (I think Image is the only one that has it). Rename it to something that makes sense
2. Replace all places in the test for that class in `tests`. Run the tests and make sure they pass.
3. Replace all places in the code where that property occurs. Make sure you test out your changes with some docker images
4. Repeat for classes with `license` as the property (I think package is the only one that has that for now)

Feel free to submit 2 PRs - one for the `id` replacement and one for the `license` replacement.

Don't hesitate to ask any questions. Thanks for working on this!

**Comment by ManishaTripathy** [comment]
I see id in docker_image.py and image.py. Do we need to replace both or just image_py?
After replacing, we need to run only the changed tests or all tests in general?

**Comment by nishakm** [comment]
@ManishaTripathy good catch! Please replace `id` in both `image.py` and `docker_image.py`. Hold off on the tests. Let me see if they pass now.

**Comment by nishakm** [comment]
@ManishaTripathy currently only `test_class_image.py` passes. `test_class_docker_image.py` needs some work still so no need to run that one. The Travis build should cover that case.

**Comment by nishakm** [comment]
Resolved in #231 and #233
