### ISSUE TITLE
Should we only pin up to a minor version?

### ISSUE THREAD

**Issue by SantiagoTorres** [vmware/tern#236]
**Problem Statement**
The way we are defining requirements in `requirements.txt` and `setup.py` pin up to the patch version on dependencies. This seems a little bit too strict for downstream packagers. 

**Describe the Proposal**
We should pin the dependencies up to the minor version only using the syntax defined on [PEP-0440](https://www.python.org/dev/peps/pep-0440/#compatible-release)

**Steps to Implement Proposal**
I'm assuming we can basically `sed -i 's/==/~=/g' requirements.txt'`, but we may want to test things first :)

**Comment by nishakm** [comment]
Great suggestion! I'm bumping up versions in the next release. I can test it out then.

**Comment by nishakm** [comment]
@SantiagoTorres do you know if there is any way to override the `requirements.txt` file in `setup.py`? This is to pin the dependencies to the patch version for all direct and indirect dependencies for a particular release.

**Comment by SantiagoTorres** [comment]
Hmmm, interesting. `setup.py` reads `requirements.txt` dynamically at build/dist/sdist time, so I'm sure we can add some logic in there, but I'd have to dig in and figure what's the best way forward. I'll keep you posted!

**Comment by nishakm** [comment]
So I think for now, we will just create a release.txt file that will have the full requirement list for informational purposes and pin the requirements.txt file to just the minor version.
