### ISSUE TITLE
Create Dockerfile to 'try it out'

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#24]
The Dockerfile allows for another type of isolation and can be run in two steps if one is using Docker.

Requirements:
- Import from a known baseOS against which Tern has been run and verified
- Install packages with specific versions
- Include a Tern report with a disclaimer to not distribute without going through the licenses of the included packages

See https://github.com/vmware/tern/issues/23 for a Dockerfile that will work with Tern. Try using PhotonOS as their license metadata is concise.

**Comment by nishakm** [comment]
@tojo13 is working on this issue

**Comment by jtcasper** [comment]
Is this still in progress? Is it necessary to run the Dockerfile as `--privileged` so that it is allowed to use `mount`?

**Comment by nishakm** [comment]
@jtcasper, for some reason your comment (sent to my email) doesn't show up here: Is this still in progress? Is it necessary to run the Dockerfile as --privileged so that it is allowed to use mount?

It might be necessary. I have not tried it yet. I think @tojo13 might be busy with other stuff, so if you want to check it out, that's totally fine and I would appreciate it :)

It also could become a higher priority based on work required to make it work as a web service (#65)

**Comment by gregwebs** [comment]
The code currently invokes "docker" as a cli. This makes it trickier: it requires at least an extra install of docker in the docker image. This process would be easier if the code used the docker API: that would only require mounting the docker socket.

**Comment by nishakm** [comment]
There's another proposal to replace the existing docker cli wrapper with the python library for the docker engine API: https://github.com/vmware/tern/issues/41. @gregwebs can you give an example of how to replace a docker cli command like `docker pull` with the API?

**Comment by nishakm** [comment]
I've gotten as far as creating a Docker container with tern in it. However, in order to analyse an image, it needs to pull it first.

**Comment by nishakm** [comment]
I've hit an inconvenience:
For OSs that enable SELinux, any containerized process is denied permission to /var/run/docker.sock. In this case, the container needs to run as privileged.

**Comment by nishakm** [comment]
First real roadblock: mount and unshare not found in container image:
```
root [ / ]# ./tern -l report -i photon:3.0
2019-02-06 23:01:43,843 - DEBUG - tern - Starting...
2019-02-06 23:01:43,845 - DEBUG - report - Setting up...
2019-02-06 23:01:43,846 - DEBUG - container - Checking if image photon:3.0 is available on disk...
2019-02-06 23:01:43,852 - DEBUG - container - Image photon:3.0 found
2019-02-06 23:01:44,694 - DEBUG - rootfs - Running command: ./tools/fs_hash.sh /temp/33df97c5dff4c19d8b09b5c728e8ac3efba0b2655656c0159ecf5635886d5322/contents
2019-02-06 23:01:45,564 - DEBUG - rootfs - Running command: mount -o bind temp/33df97c5dff4c19d8b09b5c728e8ac3efba0b2655656c0159ecf5635886d5322/contents temp/mergedir
Traceback (most recent call last):
  File "./tern", line 103, in <module>
    main(args)
  File "./tern", line 54, in main
    report.execute_docker_image(args)
  File "/report/report.py", line 413, in execute_docker_image
    analyze_docker_image(full_image, args.redo)
  File "/report/report.py", line 177, in analyze_docker_image
    target = rootfs.mount_base_layer(image_obj.layers[0].tar_file)
  File "/utils/rootfs.py", line 110, in mount_base_layer
    root_command(mount, base_rootfs_path, target_dir_path)
  File "/utils/rootfs.py", line 54, in root_command
    stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mount': 'mount'
```

**Comment by nishakm** [comment]
And we come to the real problem:
```
# mount -t overlay overlay -o lowerdir=temp/0368f25553be7c038bef63f01e55168a10758643b5643f680d7f3606863afa4b/contents,upperdir=temp/bea60c50f6fd6b0b7a9a3d6253b79b472ea00294dea6fba3f157c97997873524/contents,workdir=temp/workdir temp/mergedir
mount: /temp/mergedir: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
```

**Comment by nishakm** [comment]
There are some issues with regards to running Tern in a Docker container:
1. Tern uses `mount` which is gated by CAP_SYS_ADMIN, i.e. all the restrictions need to be open in order to run `mount` from within a container.
2. Most of the time, the filesystem within a container is `overlay`. You cannot mount an overlayfs on top of another overlayfs filesystem.

To solve 1, you need to run the container as privileged using `docker run --privileged`. To solve 2, you need to bind mount a host directory using `--mount`. This is essentially giving a root user access to the host's filesystem binaries. If the script gets terminated prematurely, those host system's binaries remain and the root user can invoke any of them. You'll have to be very very careful with this container.
