### ISSUE TITLE
Add a test for get_package_id method in Package class

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#251]
**Description**
Add a test in `tests/test_class_package.py` called testGetPackageId

**Implementation**
Check to see if the method returns a string containing the package name and version.
For example, the test currently has an object `self.p1`. Test if `self.p1.get_package_id` returns "p1.1.0"

Make sure the tests in `test_class_package.py` pass.
```
pip install .
python tests/test_class_package.py
```
**References**
See other tests in `test_class_package.py` for reference

**Super Issues**
#239

**Comment by nishakm** [comment]
@rnjudge Would you like to try this one?

**Comment by rnjudge** [comment]
@nishakm sign me up!

**Comment by nishakm** [comment]
@rnjudge awesome! It's yours.
