### ISSUE TITLE
Add 'checksum_type' to checksums

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#271]
**Problem Statement**
There are other hashing algorithms than SHA256 that tools can use

**Describe the Proposal**
Incorporate checksum_type into ImageLayer and Image classes

**Steps to Implement Proposal**
1. Modify the classes and tests such that there is a `checksum_type` property and a `checksum` property. See how the FileData class implements this.
2. Modify places in the code where `SHA256` is hardcoded. Use the `checksum_type` property instead.

**Comment by mukultaneja** [comment]
@nishakm, I have submitted a pull request to address this issue https://github.com/vmware/tern/pull/616/commits/67f8bbe8db69fc829821431ac73540b7f416ac82. Please review it. I still need to work on `Step 2`.

**Comment by rnjudge** [comment]
> @nishakm, I have submitted a pull request to address this issue [67f8bbe](https://github.com/vmware/tern/commit/67f8bbe8db69fc829821431ac73540b7f416ac82). Please review it. I still need to work on `Step 2`.

Can you open this as a separate pull request for this issue? Right now it is appended to PR https://github.com/vmware/tern/pull/616

**Comment by mukultaneja** [comment]
Hi @nishakm, I have opened a new PR https://github.com/vmware/tern/pull/617. Please review it.
