### ISSUE TITLE
Convert short names of modules to the full name

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#29]
For example:
from utils import dockerfile as df

Convert that to:
from utils import dockerfile

It would require substituting df in the module file with dockerfile

Note: multiple people can work on this issue - just note which files you are working on in the comments. If anyone would like to take this on, please look at the comments and see which files have been picked up.

**Comment by nishakm** [comment]
Can you hold off on this one for a bit? There is a big merge coming down the pipeline. It should be a couple more weeks.

**Comment by Vexxorian** [comment]
Will [that](https://gist.github.com/Vexxorian/d2c5a33e5f232277fe8beb4a8155e16f) work? Not sure if good or bad idea \\o/

**Comment by nishakm** [comment]
The reason for converting the short names to the full module names is for the sake of readability - you will be able to find the source files faster. So no :)

**Comment by MattAlp** [comment]
@nishakm first timer here, is this being held off as requested or still open? It shouldn't take more than 10-15 minutes

**Comment by nishakm** [comment]
Big merge completed! This issue is up for grabs.

**Comment by vladn90** [comment]
@nishakm Hello! Is issue still open? I'd be glad to work on it :)

**Comment by nishakm** [comment]
@vladn90 it's still open. It's a pretty big undertaking so it's fine if you focus on a couple of files at a time. I'll put this note in the issue.
