### ISSUE TITLE
pip install fails with missing dependency for wheel on Ubuntu 18.04 

### ISSUE THREAD

**Issue by davidgibsonadi** [vmware/tern#294]
**Describe the bug**
When following the installation instructions for Linux, using Ubuntu 18:04 (from the docker ubuntu:18.04 docker image) I get a failure when running setup.py for bdist_wheel

**To Reproduce**
1. Create docker image using the following dockerfile:
  FROM ubuntu:18.04
  WORKDIR /tern
  RUN apt-get update
  RUN apt-get install -y git docker python3 python3-venv
  RUN git clone  https://github.com/vmware/tern.git
2. Build the docker image:
  docker build . -t tern-docker-image
3. Launch the docker image:
  docker run -it tern-docker-image
4. Execute the following commands in the docker image to see the error:
  cd /tern
  python3 -m venv ternenv
  source ternenv/bin/activate
  cd tern
  pip install .
**Error in terminal**
```
Building wheels for collected packages: PyYAML
  Running setup.py bdist_wheel for PyYAML ... error
  Complete output from command /tern/ternenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g5yh14jj/PyYAML/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpb8ckvy42pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'
```

**Expected behavior**
It should install the dependencies.

**Environment you are running Tern on**
Docker image ubutnu:18.04
**Workaround**
Execute: pip install wheel before executing pip install .

**Comment by nishakm** [comment]
@davidgibsonadi Thanks for filing an issue! Tern won't run in a Docker container unless it is privileged and has access to the host machine at this time. Try following these instructions: https://github.com/vmware/tern#getting-started-with-docker

**Comment by davidgibsonadi** [comment]
Thanks @nishakm  sorry I should have looked there first :)

**Comment by nishakm** [comment]
Also, using `pip3 install .` rather than `pip install .` should get rid of the `bdist_wheel` error.
