### ISSUE TITLE
Commit message linter only checks top-most commit in a git tree

### ISSUE THREAD

**Issue by joshuagl** [vmware/tern#309]
**Describe the bug**
The git commit linter `test_commit_message.py` introduced in #302 only checks the git `HEAD` (usually the top-most commit in the current git branch). Therefore for multi-patch pull requests only the final patch has its commit message linted.

**To Reproduce**
1. add a commit that violates the commit message policy to tern
2. add a commit that complies with the commit message policy for tern
3. run the commit message linter in the way defined in `.circleci/config.yml` -- `python tests/test_commit_message.py`
4. observe that the linter returns without error

**Expected behavior**
The linter should check each commit in the PR. 

A reasonable approach might be to split the linting logic into a function, compare the current branch to origin/master and run the linter against each message that exists in the current branch but not in origin/master.

The error message will need be updated, I'd like to see it report the short commit hash (`git rev-parse --short COMMITSHA`), and perhaps the title, of the message which triggered an error, rather than just the offending line. That would make it easier to find the offending commit in an interactive rebase.

**Comment by nishakm** [comment]
We expected CircleCI to run the test on every commit in a PR but apparently it doesn't. So we'll put in a fix. Thanks for catching it!
