### ISSUE TITLE
Remove bandit from circleci

### ISSUE THREAD

**Issue by rnjudge** [vmware/tern#321]
**Description**
We had initially enabled Bandit in circleci when we thought that Prospector was interfering with running circleci properly. Now that Prospector and circleci are running in harmony we can disable Bandit from running for each PR.

**To Do**
In .circleci/config.yml. 
1) Remove the 'security' job:
#security linting using Bandit
 security:
   executor: ubuntu1604
   steps to run Bandit
   steps:
     - setup
     - run: pip install -r dev-requirements.txt
     - run: bandit -r .
2) Remove the workflow named 'security' under the jobs list.

**Background**
See description.

**Super Issues**
None

**Comment by manaswinidas** [comment]
I'm interested to work on this issue

**Comment by rnjudge** [comment]
Closing this issue for now as Prospector only runs for PRs. Therefore, we need to keep Bandit for when we merge changes to master.
