### ISSUE TITLE
Deprecate the default verbose report

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#363]
**Problem Statement**
The default verbose report is too long and has too much information for any person to sift through.

**Describe the Proposal**
Either replace the verbose report or replace it with a report that summarizes the general nature of the container image. It can contain:
* What BaseOS if Tern can find it
* Only report on package names and their versions
* Give a summary of licenses found

**Steps to Implement Proposal**
* Convert the default report into a plugin
* If no plugin is chosen in the command line, replace it with this plugin
* Remove the current summary report

**Comment by rnjudge** [comment]
I think there are circumstances where it might still be useful to generate a verbose report. What about moving the verbose functionality into its own plugin while still deprecating the default verbose report in favor of something more concise?

**Comment by nishakm** [comment]
> I think there might circumstances where it might still be useful to generate a verbose report. 
Such as? We already have a JSON and YAML report that dumps everything into a file or to screen.

> What about moving the verbose functionality into its own plugin while still deprecating the default verbose report in favor of something more concise?

This could work. I used to think that the verbose report should be the default report but I'm beginning to think that it doesn't help to have so much information in one place. It can be overwhelming. Instead, an idea of what the container looks like and what license issues it might have would be more useful as the default format.
