### ISSUE TITLE
Add a yaml file dependency document that lists transitive dependencies

### ISSUE THREAD

**Issue by rnjudge** [vmware/tern#374]
**Problem Statement**
When we cut a release, it would be helpful to see a list of all the dependencies, ordered by which package pulls them in. 

**Describe the Proposal**
List these dependencies in yaml format so we can easily parse the list later down the road.

**Steps to Implement Proposal**
pip freeze will give you the list of deps but not which are transitive and which are the primary requirement. Use a package manager like npm to help sort which are transitive and which package pulls them in.

**Comment by nishakm** [comment]
Closing this in favor of using pip-tools.
