### ISSUE TITLE
Revisit CLI options

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#390]
**Problem Statement**
The command line options seem cluttered. Let's try to structure them better

**Describe the Proposal**
Because we are dealing with user interface and downstream use, this will break API and hence qualify for a major version increase

**Comment by rnjudge** [comment]
Since separating the json and yaml options into their own plugins, there is no longer information about how to collect json or yaml reports in the --help output:

```
(ternenv) rjudge@ubuntu:~/ternenv/tern$ tern --help
usage: Tern [-h] [-l] [-c] [-k] [-b] [-r] [-V] {report} ...

           Tern is a container image component curation tool. Tern retrieves
    information about packages that are installed in a container image.
    Learn more at https://github.com/vmware/tern

positional arguments:
  {report}              Subcommands
    report              Create a report

```

More information about how to use the report -m option might be helpful for users.

**Comment by nishakm** [comment]
You have to do `tern report -h` to get the subparser options. Perhaps the description can be changed from `Create a report` to `Create a BoM report. Run 'tern report -h' for command line options` or something like that.

**Comment by rnjudge** [comment]
What else would you like to see cleaned up on the command line?

**Comment by nishakm** [comment]
> @nishakm What else would you like to see cleaned up on the command line?
`-V, --version         show program's version number and exit`
Maybe this should be `-v`?

```  
-k, --keep-working-dir
                        Keep the working directory after execution;Useful when debugging container images
```
Maybe a shorter `--` option

```
  -b, --bind-mount      Treat working directory as a bind mount;Needed when running from within a container
```
Maybe change `;` into `.` and same thing for the -k option?

```
$ tern report -h
usage: Tern report [-h] [-d DOCKERFILE] [-i DOCKER_IMAGE] [-s]
                   [-m REPORT_MODULE] [-f FILE]

optional arguments:
  -h, --help            show this help message and exit
  -d DOCKERFILE, --dockerfile DOCKERFILE
                        Dockerfile used to build the Docker image
  -i DOCKER_IMAGE, --docker-image DOCKER_IMAGE
                        Docker image that exists locally - image:tag The
                        option can be used to pull docker images by digest as
                        well - <repo>@<digest-type>:<digest>
  -s, --summary         Summarize the report as a list of packages with
                        associated information
  -m REPORT_MODULE, --report-format REPORT_MODULE
                        Format the report using one of the available formats:
                        spdxtagvalue, json, yaml
  -f FILE, --file FILE  Write the report to a file; If no file is given the
                        default file in utils/constants.py will be used
```

What do you think about using `-f REPORT_FORMAT, --report-format REPORT_FORMAT` and then using `-o FILE, --output-file FILE`. This way we can use `-m` for something else that might come up.

**Comment by rnjudge** [comment]
> > @nishakm What else would you like to see cleaned up on the command line?
> > `-V, --version         show program's version number and exit`
> > Maybe this should be `-v`?

I have seen -v typically used for verbose mode. Do you ever think we will want a verbose report? (I think I already asked you this question in issue #363 but it comes up again)

> ```
> -k, --keep-working-dir
>                         Keep the working directory after execution;Useful when debugging container images
> ```
> 
> Maybe a shorter `--` option

Agree. Maybe --keep-wd? --kwd to me looks like three different arguments but maybe that's just me.

> ```
>   -b, --bind-mount      Treat working directory as a bind mount;Needed when running from within a container
> ```
> 
> Maybe change `;` into `.` and same thing for the -k option?

Sounds good.

> 
> ```
> $ tern report -h
> usage: Tern report [-h] [-d DOCKERFILE] [-i DOCKER_IMAGE] [-s]
>                    [-m REPORT_MODULE] [-f FILE]
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   -d DOCKERFILE, --dockerfile DOCKERFILE
>                         Dockerfile used to build the Docker image
>   -i DOCKER_IMAGE, --docker-image DOCKER_IMAGE
>                         Docker image that exists locally - image:tag The
>                         option can be used to pull docker images by digest as
>                         well - <repo>@<digest-type>:<digest>
>   -s, --summary         Summarize the report as a list of packages with
>                         associated information
>   -m REPORT_MODULE, --report-format REPORT_MODULE
>                         Format the report using one of the available formats:
>                         spdxtagvalue, json, yaml
>   -f FILE, --file FILE  Write the report to a file; If no file is given the
>                         default file in utils/constants.py will be used
> ```
> 
> What do you think about using `-f REPORT_FORMAT, --report-format REPORT_FORMAT` and then using `-o FILE, --output-file FILE`. This way we can use `-m` for something else that might come up.

Works for me.

**Comment by nishakm** [comment]
> I have seen -v typically used for verbose mode. Do you ever think we will want a verbose report? (I think I already asked you this question in issue #363 but it comes up again)

I like the idea you proposed to move the verbose report to its own plugin. In which case `v` for `verbose` will not be needed. We have `-l` which is kindof what `verbose` means in other tools i.e. be talkative during execution.

> Agree. Maybe --keep-wd? --kwd to me looks like three different arguments but maybe that's just me.

I think it's enough to say --keep-wd
