### ISSUE TITLE
Run tests using `python3 setup.py test`

### ISSUE THREAD

**Issue by PrajwalM2212** [vmware/tern#406]
**Problem Statement**
The command `python3 setup.py test` is not running the tests.

**Describe the Proposal**
`python3 setup.py test` should be able to run all the tests.
Such functionality will help the developers to know if they are breaking anything with their new features.

**Steps to Implement Proposal**
1. Reorganise import statements in the test files.
2. Add a function in setup.py to load test_suite

**Comment by nishakm** [comment]
@PrajwalM2212 do you want to try incorporating this?

**Comment by PrajwalM2212** [comment]
Yes, Give me a couple of days.

**Comment by nishakm** [comment]
Closing as we can now run tests using `tox`.
