### ISSUE TITLE
Add test-coverage 

### ISSUE THREAD

**Issue by PrajwalM2212** [vmware/tern#407]
**Problem Statement**
There must be a way to know the current coverage

**Describe the Proposal**
Currently, tern does not have a feature to know the current test coverage.
Have test coverage is important to make sure that untested code does not get 
merged.

**Steps to Implement Proposal**
Install and configure `coverage`

**Comment by rajibmitra** [comment]
I would love to work on this , if  needed.

**Comment by nishakm** [comment]
@rajibmitra Do you still want to incorporate `coverage`?
