### ISSUE TITLE
Proposal: Replace docker_command wrapper with docker-py python module

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#41]
The docker-py python module can be used to invoke the Docker Engine API. This means replacing all of the subprocess commands in container.py with the docker-py API. This invariably means nuking container.py 

https://github.com/docker/docker-py

**Comment by jeevers** [comment]
I can work on this!

**Comment by nishakm** [comment]
assigned to @jeevers

**Comment by nishakm** [comment]
Duplicate of #148
