### ISSUE TITLE
UBUNTU (DEBIAN TOO?) LIMITS THE NUMBER OF TIMES YOU CAN USE MERGEDIR

### ISSUE THREAD

**Issue by snmpboy** [vmware/tern#43]
Trying to mount a third filesystem layer to mergedir does not work on Ubuntu server.

Output below is from following the manual python commands in issue #37 in iPython.
In [110]: rootfs.mount_diff_layer(d.layers[2].tar_file)
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-110-cbeab329b745> in <module>()
----> 1 rootfs.mount_diff_layer(d.layers[2].tar_file)

~/PycharmProjects/tern/utils/rootfs.py in mount_diff_layer(diff_layer_tar)
    116     args = 'lowerdir=' + merge_dir_path + ',upperdir=' + upper_dir_path + \
    117         ',workdir=' + workdir_path
--> 118     root_command(union_mount, args, merge_dir_path)
    119     prep_rootfs(merge_dir_path)
    120 

Refer to #37 for more information

**Comment by nishakm** [comment]
@snmpboy is working on this issue

**Comment by snmpboy** [comment]
I tried updating my Ubuntu server to 18.04.  Parallels is the hypervisor on my mac.  Beware it does not support the kernel that comes with Ubuntu 18.04.

**Comment by nishakm** [comment]
@snmpboy let's close this as we have gotten this to work on an 18.04 Vagrant box
