### ISSUE TITLE
Create an analyzed_output property for each layer with appropriate tests

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#445]
***Description***
Create a property called `analyzed_output` in the ImageLayer class located in `tern/classes/image_layer.py`.

***Implementation***
In `tern/classes/image_layer.py`:

1. Add `analyzed_output` to class docstring under class ImageLayer:
`analyzed_output: the result of the file analysis`.
2. Add the property to `__init__` function and set it to an empty string.
3. Add a getter and setter. The setter should check if the input is a string and if not, then raise a ValueError with a message like "analyzed_output should be a string"

In `tests/test_class_image_layer.py`, add tests for files_analyzed in `testInstance`:
1. Test if the default value is and empty string.
2. Test if the value can be set to any string.
3. Test if a ValueError is raised if you set it to an `int`.

References
Look in tern/classes/image_layer.py and tests/test_class_image_layer.py to see examples of how to implement this.

Super Issues
#284

**Comment by manaswinidas** [comment]
I'm interested to work on this.

**Comment by nishakm** [comment]
@manaswinidas sure!
