### ISSUE TITLE
Set PackageDownloadLocation as NOASSERTION in SPDX tag:value report formatting

### ISSUE THREAD

**Issue by rnjudge** [vmware/tern#451]
**Description**
Currently, Tern reports the SPDX `PackagetDownloadLocation` of an image layer as the docker image repotag. This does not reflect the actual download location and there is no way for Tern to pinpoint the download location of an image layer. Therefore, we should assign the SPDX `PackageDownloadLocation` value as NOASSERTION in accordance with the 2.1 spec. We can also remove the `get_download_location` function in `docker_image.py`

**Implementation**
1) In `tern/formats/spdx/spdxtagvalue/generator.py`, remove the `registry_repotag` variable assignment in the following lines:
```
235         # The image's PackageDownloadLocation is from a container registry      
236         # This includes all the layers but the packages' download location      
237         # is unknown if the download_url is blank                               
238         registry_repotag = image_obj.get_download_location() if hasattr(        
239             image_obj, 'repotag') else 'NOASSERTION'
```
2) In `tern/formats/spdx/spdxtagvalue/generator.py`, hardcode the `PackageDownloadLocation` value as `NOASSERTION`:
```
265                 PackageDownloadLocation=NOASSERTION,
```
3) In `tern/classes/docker_image.py` remove the definition for `get_download_location()` since it is not possible to get the actual location (dockerhub.io is not the actual location).
```
171     def get_download_location(self):                                            
172         '''A docker image's download location is in the repotags. We will       
173         return a string of repotags joined by a hyphen -'''                     
174         return '-'.join(self.repotags)
```

**References**
See above.

**Comment by manaswinidas** [comment]
I'm interested to take this up.

**Comment by nishakm** [comment]
@manaswinidas yeah! Go for it!

**Comment by manaswinidas** [comment]
@nishakm Do I still have to follow the instructions mentioned in #449 for not getting the extra commits?

**Comment by manaswinidas** [comment]
Never mind, I found my way :sweat_smile: but do I have to do this every time:cry: ?

**Comment by nishakm** [comment]
> Never mind, I found my way 😅 but do I have to do this every time😢 ?

I hope not! 😅

If you want to set up your local fork of tern to continue to contribute, follow the instructions here: https://github.com/nishakm/puns#how-to-submit-prs-with-your-github-fork

Everytime you need to submit a new PR you create a new branch to track the upstream master branch:
`git checkout -b 451-my-changes --track upstream/master`

When you need to update this because of a conflict or to pull in newly merged changes, run:
`git pull --rebase`

I hope you don't have trouble next time around.

**Comment by manaswinidas** [comment]
@nishakm you were right about this. It worked perfectly fine! Thanks :tada: 

> Everytime you need to submit a new PR you create a new branch to track the upstream master branch:
> `git checkout -b 451-my-changes --track upstream/master`
