### ISSUE TITLE
Produce a "pinned" Dockerfile when provided a regular Dockerfile

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#454]
**Describe the Feature**
Tern currently has the ability to build a docker image given a Dockerfile and then analyze that docker image while annotating to the report information about the Dockerfile line that created the image. Why not use the same functionality to produce an annotated Dockerfile with all the versions pinned to the versions tern finds? This works like a "pip freeze" in python.

**Use Cases**
Container developers can try to achieve a somewhat repeatable build with a pinned Dockerfile rather than a regular Dockerfile.

**Implementation Changes**
1. This requires some moving around of command line arguments. Probably the `-i` and `-d` arguments should be top level options rather than report level options.
2. The implementation should be straightforward as `tern/utils/dockerfile.py` has a parser and functions to gets individual instructions.

**Comment by nishakm** [comment]
@joshuagl

**Comment by nishakm** [comment]
Here's an outline of what I spoke with @rnjudge about:
```
FROM debian:buster --> FROM debian@sha256:12345 # pin to specific image
ARG variable=$value --> ARG variable=actual_value # trouble here as sometimes passwords get passed
RUN apt-get update && apt-get install ca-certificates... --> RUN apt-get install ca-certificates-1.2.3 # only install specific versions
ADD tar /folder --> ADD tar /folder # git project name and sha if any

**Comment by joshuagl** [comment]
I put together a really dumb prototype to do the first suggestion and a bit of the second with [docker/docker-py](https://github.com/docker/docker-py/) and [containerbuildsystem/dockerfile-parse](https://github.com/containerbuildsystem/dockerfile-parse). 

Forgive the unfinished state of the code, this was the result of a short spurt of prototyping that I hope is worth sharing [`test.py`](https://gist.github.com/joshuagl/2d30d79373f87858db9863d2a44d6150).

One thing I did want to play with was freezing the apt metadata on Debian based images by removing the standard Debian apt sources and adding a [snapshot.debian.org](https://snapshot.debian.org) entry for  yymmddThhmmssZ (which gives you the most recent snapshot before the specified time). I hoped to look at other distros and see if they have a similar mechanism available for pinning the package manager metadata, but didn't get back to this idea yet.

Extremely happy to see you adding this to Tern! 🎉

**Comment by nishakm** [comment]
> I put together a really dumb prototype to do the first suggestion and a bit of the second with [docker/docker-py](https://github.com/docker/docker-py/) and [containerbuildsystem/dockerfile-parse](https://github.com/containerbuildsystem/dockerfile-parse).

I'll check out dockerfile-parse! I wrote a parser of my own but it's not very sophisticated.

> One thing I did want to play with was freezing the apt metadata on Debian based images by removing the standard Debian apt sources and adding a [snapshot.debian.org](https://snapshot.debian.org) entry for yymmddThhmmssZ (which gives you the most recent snapshot before the specified time).

That would be super cool! Tern just runs `dpkg --get-selections` at each layer to see what got installed. It would be nice if we could find out when things got installed during layer creation and update the sources at that time before running this.
