### ISSUE TITLE
Add cache.yml to .gitignore

### ISSUE THREAD

**Issue by tojo13** [vmware/tern#48]
We do not want to track changes to `cache.yml` through git.

**Comment by tojo13** [comment]
I can work on this.

**Comment by nishakm** [comment]
@tojo13 is working on this

**Comment by nishakm** [comment]
Ah, so it didn't work :) Maybe there's another way to get git to stop tracking cache.yml?

**Comment by nishakm** [comment]
Turns out you can't stop tracking a file after a certain commit. So added instructions on how to deal with it in the docs: https://github.com/vmware/tern/commit/06312e813ef27bc0bcc0803d179c56ec008d1028
