### ISSUE TITLE
Make `bin/activate` be able to run from other shells

### ISSUE THREAD

**Issue by silverhook** [vmware/tern#484]
**Describe the bug**

Running `bin/activate` fails on shells that are not Bash.

**To Reproduce**
1. follow the instructions in `README.md`
2. get to the point where you need to execute `source bin/activate` and do that
3. See error

**Error in terminal**
```
bin/activate (line 74): Missing end to balance this if statement
if [ -n "${BASH:-}" -o -n "${ZSH_VERSION:-}" ] ; then
^
from sourcing file bin/activate
        called on standard input

source: Error while reading file “bin/activate”
```

This happens on Fish Shell, but I expect the same would be true in some others as well.

**Expected behavior**

To be fair, the `bin/activate` file does state it requires to be ran from Bash. But I see no reason for this.

Wouldn’t a hashbang to explicitly demand bash solve this issue, e.g. as `#!/usr/bin/env bash` or just `#!/bin/bash`

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version' – did not get to that part. I am trying to install from commit 68cb1250db29dfc33c5e93b0ad63b9955845b6c2
- Operating System: Ubuntu 18.04.3 LTS
- Python version 3.6.8
- local laptop install

**Comment by rnjudge** [comment]
Hi @silverhook, I'm sorry to hear you are having trouble getting your virtual environment to activate with your Fish Shell!

I looked around for others having the same issue and found this [reference](https://github.com/pypa/virtualenv/issues/853). Looks like there is an activation script especially for the Fish shell. Please try to run:
```source bin/activate.fish```

I think this issue you raised is good justification to perhaps make a small edit to our documentation to specify that the directions to activate a virtual environment we have there are specificailly for bash. I will do that now and then close out this issue. Please let me know if you have any further questions.

**Comment by silverhook** [comment]
@rnjudge Thanks, this fixed this issue for me. 

One small typo creaped into https://github.com/vmware/tern/pull/485 though – there should be a space between `source` and `bin/activate.fish` (and the same with csh).

Also, I apologise for the late reply …life happens, sometimes in an ugly way.
