### ISSUE TITLE
CLI: Make logging the default behavior and add a quiet option

### ISSUE THREAD

**Issue by rnjudge** [vmware/tern#490]
**Problem Statement**
Currently Tern's default mode of operation is to run quietly unless logging (-l option) is provided. The logging option is useful for users (especially new ones) and should be enabled by default, especially since all of our documentation and tutorials instruct users to run with the -l option.

**Describe the Proposal**
I propose to make logging the default mode of operation for Tern and replace the logging option with a quiet (-q) option if users don't want the logging behavior. This will unfortunately change the command line options and likely constitute another major release since it will not be backwards compatible so there is no rush on the implementation of this feature.

**Steps to Implement Proposal**
1) Remove -l, logging option from the command line options and make it's behavior default.
2) Add a -q, --quiet option to the command line which silences the output to the terminal while Tern runs.

**Comment by PrajwalM2212** [comment]
I will do this, if we need it now.
` This will unfortunately change the command line options and likely constitute another major release since it will not be backwards compatible so there is no rush on the implementation of this feature.`
@nishakm @rnjudge Should I try this or should this be left for some time in future.

**Comment by nishakm** [comment]
@PrajwalM2212 it's not pressing and I would like to break it down into a few good-first-issues for other people to take a crack at. What do you think?

**Comment by PrajwalM2212** [comment]
@nishakm Agreed. We do need some good-first-issues.

**Comment by radmirnovii** [comment]
Hi, found your project in GSoC organizations and decided start with this small contriburion
