### ISSUE TITLE
Build containers to inspect them layer by layer

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#5]
Building a container from a Dockerfile means expressing the union of all of the diff filesystems, which means inspecting them within a container cannot pry apart which packages are installed in which layer. There needs to be some way of 'layering up' an 'empty' container so the filesystems can be inspected one at a time.

For now we can invoke Docker's API in python and implement this (I predict this is going to be more messy than it needs to be but it gets the job done for now)

In the future, it may make sense to do this using a container runtime or something else to spin up an isolated environment to mount the filesystems on (a container runtime seems the most straightforward choice to provide a balance between ease of use, performance and portability). The choice of which container runtime, however, is yet to be made but must be made soon-ish

**Comment by tpepper** [comment]
This might be interesting as a part of a build chain like https://github.com/containerbuilding/cbi/blob/master/docs/cbi.png

**Comment by nishakm** [comment]
Some initial work on this was merged in https://github.com/vmware/tern/pull/56

It still needs root privileges to run mostly due to the fact that mounting /proc /sys and /dev is required in order to do the inspection.
