### ISSUE TITLE
docker container not accepting the parameters

### ISSUE THREAD

**Issue by pilvikala** [vmware/tern#501]
**Describe the bug**
The docker_run.sh does not accept the parameters as stated in the documentation and prints out an error.
I think this is likely related to the change made in https://github.com/vmware/tern/pull/500

**To Reproduce**
1. Clone the repository 
2. Build the container using the command provided in the readme.
3.  ./docker_run.sh workdir ternd "report -i debian:buster" > output.txt
4. The error is displayed.

**Error in terminal**
```
$ ./docker_run.sh workdir ternd "report -i debian:buster" > output.txt
usage: Tern [-h] [-l] [-c] [-k] [-b] [-r] [-v] {report} ...
Tern: error: invalid choice: '/hostmount' (choose from 'report')

```

**Expected behavior**
An output.txt file is produced with the data in it.

**Environment you are running Tern on**
Enter all that apply
Ubuntu 19.10
Python 3.7.5 and 2.7.17rc1 available on the system

**Comment by nishakm** [comment]
@pilvikala We haven't made a pypi release with the fix yet, so the container still has the old state. To build a container with the fix use these commands:
```     
python3 setup.py sdist
docker build -t ternd -f ci/Dockerfile                         
./docker_run.sh workdir ternd "report -i golang:alpine"
```
