### ISSUE TITLE
Update command parsing to detect package to be installed if version is specified

### ISSUE THREAD

**Issue by rnjudge** [vmware/tern#506]
**Description**
Each Linux package manager specifies how to install a particular version of a package differently. For example, when installing a package on a Debian/Ubuntu system, you would run `sudo apt install package=version.release` and if you were using Alpine you would similarly run `apk add packagename=1.2.3-suffix`. If you were using a Photon/CentOS/Fedora package manager like `tdnf` or `rpm` you would use `rpm -i package-version.release`. 

This parsing works towards the Dockerfile "freeze" functionality. The reason we want to be able to detect package versions that are specified is so we can automatically report the package version in the "frozen" Dockerfile without having to do the work of looking for it in the built container. 

**To Do**
1) Do some research to compare the python shlex and getopt library to see if there is a good way to use these for this bug.
2) Add a section under each package manager in `tern/command_lib/base.yml` that denotes how the package manger specifies package versions for install (i.e. `-` or `=`)
3) Update the `parse_command` function in `tern/utils/general` to recognize and record package versions when they are present after an install command.

**Super Issues**
#454

**Comment by nishakm** [comment]
This should also fix #2 - a really old bug :)

**Comment by nishakm** [comment]
Fixed in a4c107f447621defecfc227d31d043e2c3a91326
