### ISSUE TITLE
Extract the digest of a Docker image to pin for Dockerfile "freeze" functionality

### ISSUE THREAD

**Issue by rnjudge** [vmware/tern#507]
**Description**
Extract the digest of the image provided in the Dockerfile and pin it in the "frozen" Dockerfile.

**To Do**
1) This task will take some investigation as it is unclear at the time of filing this issue how we get the exact transport digest of a docker image. As far as we know, the Docker API has no way of getting the image digest if the image already exists on disk and the digest that you pull is not the same as the digest that exists when you do a docker save that you might find in the container.

2) Once (1) is determined, we will need to update the `docker_image` class to store the digest value. Currently we only store the image repo tag but we should have something to represent the digest that we pull in the Dockerfile. 

3) Add a parser in the `tern/analyze/docker/dockerfile.py` class to determine if the image digest is provided in the Dockerfile. If it is, we don't need to determine the digest in step (2) for the resulting "frozen" Dockerfile.

There is some prototyping done for this here: https://gist.github.com/joshuagl/2d30d79373f87858db9863d2a44d6150

**Super Issues**
#454

**Comment by nishakm** [comment]
Fixed in 3dbd5a037d92f00dbb7f8bf0bf72404b16bc007b
