### ISSUE TITLE
Only allow specifying an image and tag or an image digest

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#519]
**Describe the bug**
Deferring to the Python API to figure out what image to download can result in some non-deterministic action. See #510 as an example where providing an image with no tag downloads "latest" and all other available tags.

**Expected behavior**
1. The user should provide an image name of the type `image:tag`
2. The user should provide an image name of the type `image@digest_type:digest`
3. Any other style of image name should cause an error

**Environment you are running Tern on**
Enter all that apply
```
Tern version 1.0.2
Python version 3.6.9
Ubuntu 18.04 LTS
```

**Comment by PrajwalM2212** [comment]
I am working on this.
