### ISSUE TITLE
Allow user to set working directory

### ISSUE THREAD

**Issue by rnjudge** [vmware/tern#523]
**Describe the Feature**
Currently Tern runs by default in the users home directory. Add a command line option for the user to specify the working directory somewhere else. If no directory is specified by the user, Tern will continue to run in the users homes directory by default.

**Use Cases**
This option might be used if you want to run multiple Tern processes at once but can't have them operating in the same directory.

**Implementation Changes**
Add a command line option that takes a local directory. Tern will then use that input as a working directory to inventory the image.

A few considerations when making changes:
1) Cleanup needs to happen for all the Tern processes running
2) Make sure that any changes to Tern still work when running Tern inside of a container.

**Comment by abhaykatheria** [comment]
I would like to work on this issue

here's the code ,i think this will do the trick

in __main__.py
```
def change_working_dir(path):
    os.chdir(path)

parser.add_argument('-wd', '--change-wd',type=change_working_dir,
                        help=" Change the working directory ")
```
`

**Comment by rnjudge** [comment]
Hello @abhay417, the parser argument you added would be the correct start for adding the command line argument, but there would need to be other updates and logic checks in the code to actually change the directory that all the mounting is taking place. 

Take a look at `create_top_dir()` where the working directory gets created.

**Comment by abhaykatheria** [comment]
@rnjudge 
I think rootfs.py is the only place where all the logic needs to be changed.
`
def set_mount_dir(bind=None):`  -> `def set_mount_dir(bind=None,wd=none):`

```

def set_mount_dir(bind=None,wd=none):
    '''Set mount directory according to --bind-mount CLI option (or lack
    thereof). The mount_dir value is used to set the working directory
    properly in get_working_dir().'''
    global mount_dir
    if wd:
        if bind:
            mount_dir = os.path.join(wd,bind)
        else:
            dot_folder_path = os.path.join(wd,".tern")
            os.mkdir(dot_folder_path)
            mount_dir = dot_folder_path
    else:
        if bind:
            mount_dir = bind
        else:
            mount_dir = general.get_top_dir()

```

**Comment by rnjudge** [comment]
Hi @abhay417 You are close! I haven't tested this but think it could be as simple as something like:

```
def set_mount_dir(bind=None, working_dir=None):
    '''Set mount directory according to --bind-mount CLI option (or lack
    thereof). The mount_dir value is used to set the working directory
    properly in get_working_dir(). If a working directory is specified by 
    the user, use that instead of the default top level directory.'''
    global mount_dir
    if bind:
         mount_dir = bind
    else if working_dir:
         mount_dir = working_dir
    else:
         mount_dir = general.get_top_dir()
```

The bind directory is used when working in a container so essentially, this would be a working directory when using a container and shouldn't be used in conjunction with the working directory command line option.

You will also need to pass in the args.working_dir argument in `do_main()`
```75     rootfs.set_mount_dir(args.bind_mount, args.working_dir)```

**Comment by abhaykatheria** [comment]
@rnjudge i did the changes but it shows error during unmounting 
__main.py__
![Screenshot from 2020-02-28 22-45-12](https://user-images.githubusercontent.com/40055274/75570058-5cf18c80-5a7c-11ea-9364-f3c0590e2ff7.png)
rootfs.py
![Screenshot from 2020-02-28 22-45-46](https://user-images.githubusercontent.com/40055274/75570065-5f53e680-5a7c-11ea-9c2b-78f80c23abbe.png)
error mesage
![Screenshot from 2020-02-28 22-46-36](https://user-images.githubusercontent.com/40055274/75570077-64b13100-5a7c-11ea-8aea-e4480ff74afd.png)
![Screenshot from 2020-02-28 22-46-53](https://user-images.githubusercontent.com/40055274/75570085-67138b00-5a7c-11ea-94ef-fbb5f9d322da.png)

**Comment by abhaykatheria** [comment]
i did some research and found this
[http://oletange.blogspot.com/2012/04/umount-device-is-busy-why.html](http://oletange.blogspot.com/2012/04/umount-device-is-busy-why.html
)

**Comment by rnjudge** [comment]
@abhaykatheria like I said, I hadn't tested my suggestion yet :) I will take a look and get back to you. In the mean time, please feel free to debug this yourself or try other solutions you are curious about. Thanks again for your work on this!

**Comment by rnjudge** [comment]
Hi @abhaykatheria I took a look and the `set_mount_dir` directory is not what we want to change anything, apologies for that. As I had originally mentioned, `get_top_dir()` is where we want to take the `work_dir` argument. I have a working solution for this and will post shortly.

**Comment by rnjudge** [comment]
@abhaykatheria here's what worked for me:

```
diff --git a/tern/__main__.py b/tern/__main__.py
index 666a208..c75d866 100755
--- a/tern/__main__.py
+++ b/tern/__main__.py
@@ -62,19 +62,19 @@ def get_version():
     return message


-def create_top_dir():
+def create_top_dir(work_dir=None):
     '''Create the top level working directory'''
-    top_dir = general.get_top_dir()
+    top_dir = general.get_top_dir(work_dir)
     if not os.path.isdir(top_dir):
-        os.mkdir(top_dir)
+        os.makedirs(top_dir)


 def do_main(args):
     '''Execute according to subcommands'''
     # set bind mount location if working in a container
-    rootfs.set_mount_dir(args.bind_mount)
+    rootfs.set_mount_dir(args.bind_mount, args.work_dir)
     # create working directory
-    create_top_dir()
+    create_top_dir(args.work_dir)
     if args.log_stream:
         # set up console logs
         global logger
@@ -132,6 +132,9 @@ def main():
                         " when running from within a container.")
     parser.add_argument('-r', '--redo', action='store_true',
                         help="Repopulate the cache for found layers")
+    parser.add_argument('-wd', '--work-dir', metavar='PATH',
+                        help="Change default working directory to specified"
+                        "absolute path.")
     # sys.version gives more information than we care to print
     py_ver = sys.version.replace('\n', '').split('[')[0]
     parser.add_argument('-v', '--version', action='version',
diff --git a/tern/utils/general.py b/tern/utils/general.py
index 913debd..449b276 100644
--- a/tern/utils/general.py
+++ b/tern/utils/general.py
@@ -29,8 +29,10 @@ def pushd(path):
     os.chdir(curr_path)


-def get_top_dir():
+def get_top_dir(work_dir=None):
     '''Get the hidden working directory'''
+    if work_dir:
+        return os.path.join(work_dir, constants.dot_folder)
     return os.path.join(str(Path.home()), constants.dot_folder)


diff --git a/tern/utils/rootfs.py b/tern/utils/rootfs.py
index 1e9c982..0e5303f 100644
--- a/tern/utils/rootfs.py
+++ b/tern/utils/rootfs.py
@@ -45,7 +45,7 @@ union_mount = ['mount', '-t', 'overlay', 'overlay', '-o']
 logger = logging.getLogger(constants.logger_name)


-def set_mount_dir(bind=None):
+def set_mount_dir(bind=None, working_dir=None):
     '''Set mount directory according to --bind-mount CLI option (or lack
     thereof). The mount_dir value is used to set the working directory
     properly in get_working_dir().'''
@@ -53,7 +53,7 @@ def set_mount_dir(bind=None):
     if bind:
         mount_dir = bind
     else:
-        mount_dir = general.get_top_dir()
+        mount_dir = general.get_top_dir(working_dir)


 def root_command(command, *extra):
```
