### ISSUE TITLE
Include base OS value from /etc/os-release as part of Tern's data model

### ISSUE THREAD

**Issue by rnjudge** [vmware/tern#524]
**Describe the proposal**
Currently, Tern reports the base OS it finds from /etc/os-release in the output report as a notice object. Instead of reporting the OS as a notice object, propose to add the base OS value to Tern's data model so that it can be extracted directly from a JSON output report. 

I can think of a few ways to do this. There could be a `base_os` attribute in the image_layer class that would get set to the same value for each layer since they are all part of the same container with the same base OS. Or perhaps we only want to set the `base_os` value in the base image layer since doing so for every layer is a bit redundant.

**Comment by nishakm** [comment]
I think we can use the property `os_guess` in the `image_layer` class for now. We can set it for just the first layer.

**Comment by ForgetMe17** [comment]
In `tern/analyze/docker/analyze.py`, funtion `analyze_first_layer`(Line 95 and 108) does not use the return value of `common.get_os_style`. Should we set the `os_guess` as this return value to fix the issue?

**Comment by rnjudge** [comment]
@ForgetMe17 We are going to let a new contributor for the project take this on. However, if you would like to mentor him or be a resource that he can ask questions to (should they arise) please go ahead!

As far as your proposal for setting the `os_guess` value, you are very close. However, `common.get_os_style` does not actually return a value. I think we will want to use `common.get_os_release` to set the `os_guess` value. If `get_os_release` does not return a value, then we will want to use the `os_guess` value(s) from `tern/command_lib/base.yml`.

**Comment by ForgetMe17** [comment]
Yes! I am very happy to help a new contributor, and I think that I will also learn a lot from it!

**Comment by aditi137** [comment]
Hi @rnjudge I am Aditi and was assigned this issue. I am unable to pass the commit sign-off check for creating a PR. Can you please help me with it? Thanks!

**Comment by ForgetMe17** [comment]
Hi, @aditi137 . You can follow commit-message-format part in [CONTRIBUTING.md](https://github.com/vmware/tern/blob/master/CONTRIBUTING.md#commit-message-format). 
The footer of your commit message should like `Signed-off-by: Some Dev <somedev@example.com>`

**Comment by aditi137** [comment]
Hey @ForgetMe17 I did have the footer in all my commit messages. Still not sure of the issue.

**Comment by rnjudge** [comment]
> Hey @ForgetMe17 I did have the footer in all my commit messages. Still not sure of the issue.

@aditi137 The issue has to do with one of your commit message sign-offs. You have three commits that I think should be one. Try to squash them in to one commit and it will be easier to deal with the commit message. I also added a comment of the issue on the PR itself.

**Comment by aditi137** [comment]
Sorry about the multiple PRs. Really appreciate everyone's help to finally get my commit through. Thanks! 🙂 
The final PR is up #592.
