### ISSUE TITLE
Allow Tern to save to and load from FileData information from the cache

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#574]
**Description**
Although Tern can now collect FileData information and save it to the cache, it cannot load it from the cache.

**To Do**
1. Create a `fill` method for FileData class similar to the `fill` method in the Package class.
2. Update the `load_from_cache` function in `common.py` to create FileData objects from information in the cache per layer.  

**Super Issues**
#480

**Comment by PrajwalM2212** [comment]
Working on it.
