### ISSUE TITLE
File level data is not reported in default and SPDX reports

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#583]
**Describe the bug**
Currently, the file level data reported by scancode is not available either in the default or SPDX reports.

**Expected behavior**
If file level licenses are found, it should be reflected in the default and SPDX reports.

**Comment by ForgetMe17** [comment]
Is there anything i can do with this issue?

**Comment by nishakm** [comment]
I will close this one and move the SPDX specific one to the near future.
