### ISSUE TITLE
Include file level licenses in the default report

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#584]
**Description**
Include licenses found by scancode (if any) into the default report format

**Background**
This depends on https://github.com/vmware/tern/pull/582 to be merged

**Super Issues**
#583

**Comment by mukultaneja** [comment]
@nishakm, I would like to take this issue!

**Comment by nishakm** [comment]
@mukultaneja It's a high priority bug though. So we need a PR pretty quickly. If you think you can dedicate time to it, then sure.

**Comment by mukultaneja** [comment]
sure @nishakm, I will do it.
