### ISSUE TITLE
Create module to look up a container OS's package manager

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#60]
Refer to #51 for more information.

Implementation looks something like this:

1. We need a list of package managers and their names in the form of a python dictionary
[{path: /usr/bin/tdnf, name: tdnf},...]
this can live in a .yml file called 'pkg_mgr.yml' in the command_lib folder
2. A module in common.py for base OS discovery. It should return the name of the package manager

**Comment by nishakm** [comment]
@tojo13 Do you think you can take this on? It's under a release deadline so no worries if you cannot commit.

**Comment by tojo13** [comment]
Sure, I can give it a go!

**Comment by nishakm** [comment]
@tojo13 thanks! It's yours. I'll be working in parallel, but that stuff is not going to work until your PR comes in :)

**Comment by nishakm** [comment]
I will be creating a stub module in common.py:
get_base_bin(base_layer)

base_layer is the layer object. The tar file associated with the layer is in base_layer.tar_file

**Comment by nishakm** [comment]
@tojo13 I am at the point where I will need this module. So I'll be assigning it to myself. Sorry! There'll be more stuff to do and hopefully it will align when you have more time. Thanks for offering to help!

**Comment by tojo13** [comment]
No worries. Sorry I couldn't get this done earlier. Good luck!

**Comment by nishakm** [comment]
Closed in #67
