### ISSUE TITLE
Running tern in docker on windows produces no output

### ISSUE THREAD

**Issue by tevoinea** [vmware/tern#625]
**Describe the bug**
Running tern in docker on windows produces no output.

**To Reproduce**
Steps to reproduce the behavior (following the steps outlined [here](https://github.com/vmware/tern#getting-started-with-docker)):
1. `git clone https://github.com/vmware/tern.git`
2. ` docker build -t ternd .`
3. Instead of running the `./docker_run.sh` shell script, I did:

`docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock --mount type=bind,source=D:\tern\workdir,target=/hostmount --rm ternd "report" "-i" "debian:buster"`

**Error in terminal**
```
None
```

**Expected behavior**
Expecting scan results. It takes a while to run, just doesn't output anything.

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version':
`PS D:\tern> docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock --mount type=bind,source=D:\tern\workdir,target=/hostmount --rm ternd "--version"
Tern version 2.0.0
   python version = 3.7.5 (default, Mar 27 2020, 09:31:02)`
- Operating System (Linux Distro and version or Mac or Windows): *Windows*

**Please attach files if they exist**
I'm not sure where I would get them from the container.

**Comment by tevoinea** [comment]
I removed the `-q` flag from the Dockerfile to get some more insight.

Some more context:
```
getfattr: ./var/lib/systemd/deb-systemd-helper-enabled/timers.target.wants/apt-daily.timer: Operation not supported
getfattr: ./var/log/apt/eipp.log.xz: Operation not supported
getfattr: ./var/log/btmp: Operation not supported
getfattr: ./var/log/faillog: Operation not supported
getfattr: ./var/log/lastlog: Operation not supported
getfattr: ./var/log/wtmp: Operation not supported

2020-04-06 23:34:46,767 - WARNING - report - Error in loading image: Command '['/usr/lib/python3.7/site-packages/tern/tools/fs_hash.sh', '/hostmount/temp/12461fa2d30679dcb1cc04dc932e415832ac02926fdd0ab2bd884fb5e08135be/contents']' returned non-zero exit status 1.
2020-04-06 23:34:46,769 - WARNING - run - Cannot retrieve full image metadata
2020-04-06 23:34:46,769 - DEBUG - run - Teardown...
2020-04-06 23:34:46,773 - DEBUG - rootfs - Running command: rm -rf /hostmount/temp/mergedir
2020-04-06 23:34:46,776 - DEBUG - rootfs - Running command: rm -rf /hostmount/temp/workdir
2020-04-06 23:34:53,488 - DEBUG - __main__ - Report completed.
2020-04-06 23:34:53,488 - DEBUG - __main__ - Finished
```

There were lots more of those `getfattr: ...` errors.

**Comment by nishakm** [comment]
@tevoinea Thanks for filing a bug! Unfortunately, the only way to run tern on windows and macOS is using Vagrant. See instructions here: https://github.com/vmware/tern#getting-started-with-vagrant. It is on our roadmap to get tern to run without privileges in a Docker container so please stay tuned :)

**Comment by tevoinea** [comment]
@nishakm Thanks for the quick response! Tern in docker on windows was working around mid November last year, what changed? Is there a workaround for running _with_ privileges in a Docker container?

**Comment by nishakm** [comment]
> @nishakm Thanks for the quick response! Tern in docker on windows was working around mid November last year, what changed?

A lot! 😅 But thanks for noticing this. I don't remember it every working natively on Windows. We always had to run it in a Vagrant box for non-linux machines due to the use of overlayfs to "debug" the container image.

>Is there a workaround for running _with_ privileges in a Docker container?

You could try to run this using Docker-in-Docker. I've never tried it myself though.

**Comment by tevoinea** [comment]
I've figured out how to run it in Docker on Windows! Thanks for the help 😊

I think the issue was tern needs to run with privileges _in_ the container as well as the container itself running as privileged.

**Comment by nishakm** [comment]
> I've figured out how to run it in Docker on Windows! Thanks for the help 😊
> 
> I think the issue was tern needs to run with privileges _in_ the container as well as the container itself running as privileged.

Would you be open to submitting a PR with instructions on how to do it for Windows? It would just be a change to `README.md`. We'd appreciate it a lot :)

**Comment by tevoinea** [comment]
I ended up creating my own Dockerfile and installing all the dependencies required to run tern. Since I'm doing exploratory work right now, it's a pretty hacky workaround just to get things working. Would you still want that as a PR? I wouldn't mind posting the Dockerfile and some instructions here as a comment if you wanted something to point people to until you create an official solution.

**Comment by nishakm** [comment]
>Would you still want that as a PR? I wouldn't mind posting the Dockerfile and some instructions here as a comment if you wanted something to point people to until you create an official solution.

Whatever works for you. We would appreciate either one. Thanks for helping out!

**Comment by tevoinea** [comment]
I started the process on my end to contribute the Dockerfile and instructions!
