### ISSUE TITLE
Enable CLI to use raw container image

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#64]
Something like 'tern report --image/-i point to a local tarball

**Comment by nilsmeyer** [comment]
I'm wondering if this could be extended to just point at a file tree, for example as part of a packer build, to create a report for a system before it's being packed into the target image format.

**Comment by nishakm** [comment]
> I'm wondering if this could be extended to just point at a file tree, for example as part of a packer build, to create a report for a system before it's being packed into the target image format.

Do you mean like the Packer example for Docker export?
```
{
  "type": "docker",
  "image": "ubuntu",
  "export_path": "image.tar"
}
```
If yes, then this is exactly what this issue is for. Basically, don't pull from a registry, create the tarball and then do the untarring, but just do the untarring.

**Comment by nilsmeyer** [comment]
Forgive me, I don't really know what the current terminology would be, what I want to be able to do is point tern at a root filesystem (or a tarball thereof) and create a report as part of building images for cloud instances (EC2 in my case) so I can use the same format for docker images as well as Machine images.

**Comment by nishakm** [comment]
It's possible to point tern to a docker image tarball, but not VMs or EC2 instances. Tern is meant solely for the container image use case. You could format the JSON output to match Packer's format. My Packer knowledge is non-existent so I can't be of much help there :(

**Comment by nilsmeyer** [comment]
My idea was the following:
1. create a tarball from an image of my VM (whatever it may be, this I believe is out of scope for tern)
2. use that tarball as the base for a single layer docker container (similarly to how many OS base images are built, FROM scratch, ADD tarfile)
3. run tern
4. ???
5. profit

I was thinking maybe it's possible to skip all the docker / OCI bits in step2 and work directly on the image.

**Comment by nishakm** [comment]
Why though? You can use the VM's package manager to list out all the installed packages. You're even welcomed to pluck the scripts from `tern/command_lib/base.yml` and write your own VM inspection thingy.

**Comment by nishakm** [comment]
Or do you specifically like the format in which the information is presented?
