### ISSUE TITLE
Complete to_dict method in image_layer class

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#86]
Currently the to_dict method in the image_layer class only includes 'packages', 'tar_file' and 'created_by'. Also include 'diff_id' and 'import_str' to the dict. See `classes/image_layer.py` for details.

This is work towards #70

**Comment by psyonara** [comment]
I'll take this one. :)

**Comment by nishakm** [comment]
@psyonara go for it!

**Comment by nishakm** [comment]
@psyonara someone has already submitted a PR for this. If you still want to work on it, let me know.

**Comment by psyonara** [comment]
@nishakm Cool, no worries. No point in duplicating work. :)

**Comment by nishakm** [comment]
https://github.com/vmware/tern/pull/97 addresses this issue. The commit message referenced the wrong issue number. Closing this.
