### ISSUE TITLE
Fill to_dict method in Image class

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#87]
See `classes/package.py` and `classes/image_layer.py` as examples.

to_dict should create a python dictionary representation of the Image object. Something like this:
```
{image: {id: <id>,
              name: <name>,
              tag: <tag>,
              manifest: <manifest dict>,
              config: <config dict>,
              layers: <result of each layer's to_dict method appended to a list>
}
```
For the layers, create an empty list and for each layer in self.layers append the result of layer.to_dict to the list

There is already a stub method in `classes/image.py` that returns an empty dictionary. This is to allow for this issue to be worked on independently of the others. Use that method to create the above dictionary.

**Comment by IpshitaC** [comment]
Hey @nishakm 
Can I take this up as a part of hacktoberfest?

**Comment by nishakm** [comment]
@IpshitaC yup! Go for it!

**Comment by nishakm** [comment]
@IpshitaC if you see a bunch of updates messages from github: that's my bad. There's a related PR already in that references this issue but is not for this issue, so it's still yours to work on. Hope to see a PR from you soon!

**Comment by IpshitaC** [comment]
Sure, I'll send in a PR soon!

**Comment by nishakm** [comment]
Fixed in https://github.com/vmware/tern/commit/8ab17e6aff0befc5704c2e60e8c41312ef7613aa
