### ISSUE TITLE
Add to_dict method to docker_image class

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#90]
The image class has a `to_dict` method which can be used by the derived class in `docker_image.py`.

The dictionary should have properties: repotag (str), repotags (list) and history (dict) along with the superclass's dictionary.

Example of how this would be implemented:
```
super_dict = super().to_dict()
super_dict.update({'repotag': self.repotag})
...
return super_dict
```
This is work towards #70

**Comment by esantoro** [comment]
Can I take this ?

**Comment by nishakm** [comment]
@TileThePlane is working on this
